package com.wpanther.xmlsigning.integration.support;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.time.Duration;
import java.time.Instant;
import java.util.UUID;

/**
 * Bootstraps eidasremotesigning for full integration tests.
 *
 * <p>On first call to {@link #setupOnce}, this helper:
 * <ol>
 *   <li>Registers an OAuth2 client at {@code POST /client-registration}</li>
 *   <li>Obtains a Bearer token via {@code POST /csc/v2/oauth2/token} (client_credentials grant)</li>
 *   <li>Inserts a BCFKS signing credential directly into the eidasremotesigning DB.
 *       The keystore file ({@code /app/keystores/eidas-signing.bfks}) is pre-mounted
 *       in the test container (see docker/docker-compose.test.yml).</li>
 * </ol>
 *
 * <p>Subsequent calls return the cached {@link SetupResult}. The Bearer token is
 * refreshed automatically when it is within 60 seconds of expiry.
 *
 * <p>Required test containers:
 * <ul>
 *   <li>eidasremotesigning on {@code localhost:9000} (started with {@code --with-eidas})</li>
 *   <li>PostgreSQL on {@code localhost:5433} (eidasremotesigning DB: {@code eidasremotesigning})</li>
 * </ul>
 *
 * <p>Start containers:
 * <pre>
 *   ./scripts/test-containers-start.sh --with-eidas --with-debezium --auto-deploy-connectors
 * </pre>
 */
public final class EidasRemoteSigningTestHelper {

    private static final Logger log = LoggerFactory.getLogger(EidasRemoteSigningTestHelper.class);

    /** Pre-mounted BCFKS keystore path inside the eidasremotesigning container. */
    private static final String BCFKS_KEYSTORE_PATH = "/app/keystores/eidas-signing.bfks";
    /** Password set by scripts/create-eidas-keystore.sh. */
    private static final String BCFKS_KEYSTORE_PASSWORD = "eidas-signing-2024";
    /** Alias generated by scripts/create-eidas-keystore.sh. */
    private static final String BCFKS_CERTIFICATE_ALIAS = "signing-key";

    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final HttpClient HTTP = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(10))
            .build();

    // --- Cached state (set once, reused across test contexts) ---
    private static volatile SetupResult cachedResult;
    private static volatile String cachedClientId;
    private static volatile String cachedClientSecret;
    private static volatile String cachedEidasBaseUrl;
    private static volatile String cachedToken;
    private static volatile Instant tokenExpiry = Instant.EPOCH;

    private EidasRemoteSigningTestHelper() {}

    /**
     * Full setup result returned to test base class.
     *
     * @param clientId     OAuth2 client ID registered in eidasremotesigning
     * @param credentialId UUID of the BCFKS signing_certificate row
     * @param accessToken  current Bearer token (refreshed automatically if near expiry)
     */
    public record SetupResult(String clientId, String credentialId, String accessToken) {}

    /**
     * Set up eidasremotesigning once; subsequent calls return the cached result.
     *
     * @param eidasBaseUrl base URL of the eidasremotesigning service, e.g. {@code http://localhost:9000}
     * @param pgJdbcUrl    JDBC URL of the eidasremotesigning database, e.g.
     *                     {@code jdbc:postgresql://localhost:5433/eidasremotesigning}
     * @param pgUser       PostgreSQL username
     * @param pgPassword   PostgreSQL password
     * @return the setup result containing clientId, credentialId, and Bearer token
     */
    public static synchronized SetupResult setupOnce(
            String eidasBaseUrl,
            String pgJdbcUrl,
            String pgUser,
            String pgPassword) {

        if (cachedResult != null) {
            return cachedResult;
        }

        log.info("[EidasTestHelper] Setting up eidasremotesigning at {}", eidasBaseUrl);
        cachedEidasBaseUrl = eidasBaseUrl;

        try {
            // Step 1: Register OAuth2 client
            ClientCredentials creds = registerClient(eidasBaseUrl);
            cachedClientId = creds.clientId();
            cachedClientSecret = creds.clientSecret();
            log.info("[EidasTestHelper] Registered OAuth2 client: {}", creds.clientId());

            // Step 2: Obtain initial Bearer token
            String token = fetchNewToken(eidasBaseUrl, creds.clientId(), creds.clientSecret());
            log.info("[EidasTestHelper] Obtained Bearer token (expires at {})", tokenExpiry);

            // Step 3: Insert BCFKS signing credential into eidasremotesigning DB
            String credId = insertBcfksCredential(pgJdbcUrl, pgUser, pgPassword, creds.clientId());
            log.info("[EidasTestHelper] Inserted BCFKS credential {} for client {}", credId, creds.clientId());

            cachedResult = new SetupResult(creds.clientId(), credId, token);
            return cachedResult;

        } catch (Exception e) {
            throw new IllegalStateException(
                    "[EidasTestHelper] Failed to set up eidasremotesigning. " +
                    "Ensure containers are running: " +
                    "./scripts/test-containers-start.sh --with-eidas --with-debezium --auto-deploy-connectors",
                    e
            );
        }
    }

    /**
     * Returns a valid Bearer token, refreshing it if it expires within the next 60 seconds.
     * Must be called after {@link #setupOnce}.
     */
    public static String getValidToken() {
        if (cachedToken != null && Instant.now().isBefore(tokenExpiry)) {
            return cachedToken;
        }
        if (cachedClientId == null || cachedEidasBaseUrl == null) {
            throw new IllegalStateException("[EidasTestHelper] Not initialized. Call setupOnce first.");
        }
        log.info("[EidasTestHelper] Refreshing OAuth2 token");
        return fetchNewToken(cachedEidasBaseUrl, cachedClientId, cachedClientSecret);
    }

    // --- Private helpers ---

    /** Registers an OAuth2 client via POST /client-registration (public endpoint, no auth). */
    private static ClientCredentials registerClient(String eidasBaseUrl) throws Exception {
        String body = MAPPER.writeValueAsString(java.util.Map.of(
                "clientName", "xml-signing-service-full-integration-test",
                "scopes", java.util.Set.of("signing"),
                "grantTypes", java.util.Set.of("client_credentials")
        ));

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(eidasBaseUrl + "/client-registration"))
                .POST(HttpRequest.BodyPublishers.ofString(body))
                .header("Content-Type", "application/json")
                .timeout(Duration.ofSeconds(15))
                .build();

        HttpResponse<String> response = HTTP.send(request, HttpResponse.BodyHandlers.ofString());
        if (response.statusCode() != 201) {
            throw new IllegalStateException(
                    "Client registration failed — HTTP " + response.statusCode() + ": " + response.body());
        }

        JsonNode json = MAPPER.readTree(response.body());
        return new ClientCredentials(
                json.get("clientId").asText(),
                json.get("clientSecret").asText()
        );
    }

    /**
     * Gets an OAuth2 Bearer token via {@code POST /oauth2/token}
     * with {@code grant_type=client_credentials} and HTTP Basic authentication.
     */
    private static String fetchNewToken(String eidasBaseUrl, String clientId, String clientSecret) {
        try {
            // Spring Authorization Server requires HTTP Basic auth for client_credentials grant
            String credentials = clientId + ":" + clientSecret;
            String basicAuth = "Basic " + Base64.getEncoder()
                    .encodeToString(credentials.getBytes(StandardCharsets.UTF_8));

            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(eidasBaseUrl + "/oauth2/token"))
                    .POST(HttpRequest.BodyPublishers.ofString("grant_type=client_credentials&scope=signing"))
                    .header("Content-Type", "application/x-www-form-urlencoded")
                    .header("Authorization", basicAuth)
                    .timeout(Duration.ofSeconds(15))
                    .build();

            HttpResponse<String> response = HTTP.send(request, HttpResponse.BodyHandlers.ofString());
            if (response.statusCode() != 200) {
                throw new IllegalStateException(
                        "OAuth2 token request failed — HTTP " + response.statusCode() + ": " + response.body());
            }

            JsonNode json = MAPPER.readTree(response.body());
            String token = json.get("access_token").asText();
            long expiresIn = json.has("expires_in") ? json.get("expires_in").asLong(3600) : 3600;
            // Expire 60 seconds early to avoid using tokens that are about to expire
            tokenExpiry = Instant.now().plusSeconds(expiresIn - 60);
            cachedToken = token;
            return token;

        } catch (IllegalStateException e) {
            throw e;
        } catch (Exception e) {
            throw new IllegalStateException("Failed to fetch OAuth2 token from eidasremotesigning", e);
        }
    }

    /**
     * Inserts a BCFKS signing_certificate row directly into the eidasremotesigning DB.
     *
     * <p>The BCFKS keystore is already present in the container at
     * {@code /app/keystores/eidas-signing.bfks} (mounted from
     * {@code docker/eidasremotesigning/keystores/eidas-signing.bfks}).
     *
     * @return the UUID of the newly inserted signing_certificate row (= the CSC credential ID)
     */
    private static String insertBcfksCredential(
            String pgJdbcUrl, String pgUser, String pgPassword, String clientId) throws Exception {

        String credId = UUID.randomUUID().toString();
        String sql = """
                INSERT INTO signing_certificates
                    (id, storage_type, certificate_alias, keystore_path,
                     keystore_password, client_id, active, created_at, description)
                VALUES
                    (?, 'BCFKS', ?, ?, ?, ?, true, CURRENT_TIMESTAMP,
                     'Integration test credential — inserted by EidasRemoteSigningTestHelper')
                """;

        try (Connection conn = DriverManager.getConnection(pgJdbcUrl, pgUser, pgPassword);
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, credId);
            stmt.setString(2, BCFKS_CERTIFICATE_ALIAS);
            stmt.setString(3, BCFKS_KEYSTORE_PATH);
            stmt.setString(4, BCFKS_KEYSTORE_PASSWORD);
            stmt.setString(5, clientId);
            int rows = stmt.executeUpdate();
            if (rows != 1) {
                throw new IllegalStateException("Expected 1 row inserted for signing_certificate, got: " + rows);
            }
        }
        return credId;
    }

    /** OAuth2 client credentials returned by /client-registration. */
    private record ClientCredentials(String clientId, String clientSecret) {}
}
